#!/usr/bin/env bash

RED='\033[1;31m'
GREEN='\033[1;32m'
BLACK='\033[1;30m'
YELLOW='\033[1;33m'
NOCOLOR='\033[0m'

diskutil list -plist external physical > ~/.disklist.plist
defaults read ~/.disklist WholeDisks > ~/.wholedisks
length=`wc -l ~/.wholedisks | sed "s/[^0-9]//g"`
disks=`cat ~/.wholedisks | sed -n "2, $((length-1))p" | tr -d ','`
numDisks=$((length-2))
rm ~/.wholedisks

if [[ $numDisks -gt 1 ]]; then
    printf "${BLACK}$numDisks Ejectable disks located\n"
elif [[ $numDisks -eq 1 ]]; then
    printf "${BLACK}$numDisks Ejectable disk located\n"
else
    printf "${RED}No disks detected\n"
    exit 1
fi

for d in ${disks[@]}
do
    printf '\t'
    diskutil eject $d
done

printf "${GREEN}Eject Complete\n"
