#!/bin/bash

rm /Users/$USER/Automation/eject/diskUtilOutput
diskutil list >> /Users/$USER/Automation/eject/diskUtilOutput
numDisks=$(Java /Users/$USER/Automation/eject/getDisks.java)
((foundDisks=$numDisks-2))
((numDisks=$numDisks-1))

if [[ $foundDisks -gt "1" ]]; then
  echo -ne $foundDisks 'Ejectable disks located. \n'
elif [[ $foundDisks -eq 1 ]]; then
  echo -ne $foundDisks 'Ejectable disk located. \n'
fi

firstPass="true"
while [[ $numDisks -gt 1 ]]; do
  if [[ $firstPass = "false" ]]; then
    echo 'done'
  fi
  firstPass="false"
  diskutil eject /dev/disk$numDisks | echo -ne 'Ejecting ~/dev/disk'$numDisks'.\n'
  echo -ne
  ((numDisks=$numDisks-1))
done

if [[ $firstPass = "true" ]]; then
  echo 'No disks Detected.'
else
  echo 'Complete.'
fi
