#!/bin/bash

numDisks=`diskutil list physical | grep -c "dev/disk"`

if [[ $numDisks -gt 2 ]]; then
  echo -ne $numDisks 'Ejectable disks located \n'
elif [[ $numDisks -eq 2 ]]; then
  echo -ne $numDisks 'Ejectable disk located \n'
fi

firstPass="true"
while [[ $numDisks -gt 1 ]]; do
  if [[ $firstPass = "false" ]]; then
    echo 'done'
  fi
  firstPass="false"
  diskutil eject /dev/disk$numDisks | echo -ne 'Ejecting ~/dev/disk'$numDisks'\n'
  echo -ne
  ((numDisks=$numDisks-1))
done

if [[ $firstPass = "true" ]]; then
  echo 'No disks Detected'
else
  echo 'Complete'
fi
